create table players (
  id bigint generated by default as identity primary key,
  name text not null,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index players_name_lower_idx on players (lower(name));

create table seasons (
  id bigint generated by default as identity primary key,
  name text not null,
  top_scores_count integer not null default 7 check (top_scores_count >= 1),
  start_date date,
  end_date date,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table events (
  id bigint generated by default as identity primary key,
  season_id bigint not null references seasons(id),
  event_date date not null,
  title text,
  notes text,
  prize_rank_1 integer not null default 1,
  prize_rank_2 integer not null default 18,
  prize_rank_3 integer not null default 25,
  status text not null default 'OPEN' check (status in ('OPEN', 'LOCKED')),
  locked_at timestamptz,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index events_season_id_idx on events (season_id);

create table event_participants (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id),
  player_id bigint not null references players(id),
  points_r1 integer check (points_r1 is null or points_r1 >= 0),
  points_r2 integer check (points_r2 is null or points_r2 >= 0),
  points_r3 integer check (points_r3 is null or points_r3 >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_id, player_id)
);

create table audit_log (
  id bigint generated by default as identity primary key,
  entity_type text,
  entity_id bigint,
  action text,
  old_value jsonb,
  new_value jsonb,
  user_id uuid references auth.users(id),
  user_email text,
  created_at timestamptz not null default now()
);

alter table players enable row level security;
alter table seasons enable row level security;
alter table events enable row level security;
alter table event_participants enable row level security;
alter table audit_log enable row level security;

create policy "authenticated_full_access" on players for all to authenticated using (true) with check (true);
create policy "authenticated_full_access" on seasons for all to authenticated using (true) with check (true);
create policy "authenticated_full_access" on events for all to authenticated using (true) with check (true);
create policy "authenticated_full_access" on event_participants for all to authenticated using (true) with check (true);
create policy "authenticated_full_access" on audit_log for all to authenticated using (true) with check (true);
